 language: node_js

 node_js:
   - "0.12"
   - "0.11"
   - "0.10"

services:
  - mongodb

 install:
  - npm install babel -g

 before_script:
  - npm install --quiet

 script:
  - make
